/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;
import bankochered.BankWindow;
import bankochered.Client;
import bankochered.ClientQuene;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Maks
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_manage = new javax.swing.JPanel();
        jSlider_speed = new javax.swing.JSlider();
        jLabel_Speed = new javax.swing.JLabel();
        jButton_nachat = new javax.swing.JButton();
        jButton_start = new javax.swing.JButton();
        jButton_stop = new javax.swing.JButton();
        jTextField_kolvoWindows = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSlider_new_clients = new javax.swing.JSlider();
        jLabel_new_clients = new javax.swing.JLabel();
        jTextField_step = new javax.swing.JTextField();
        jLabel_step = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel_window = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_window = new javax.swing.JTable();
        jLabel_kolvo_windows = new javax.swing.JLabel();
        jLabel_clients_serviced = new javax.swing.JLabel();
        jLabel_kolvo_windows_value = new javax.swing.JLabel();
        jLabel_serviced_operacion = new javax.swing.JLabel();
        jLabel_credits = new javax.swing.JLabel();
        jLabel_deposits = new javax.swing.JLabel();
        jLabel_cards = new javax.swing.JLabel();
        jLabel_payments = new javax.swing.JLabel();
        jLabel_transfers = new javax.swing.JLabel();
        jLabel_credits_value = new javax.swing.JLabel();
        jLabel_deposits_value = new javax.swing.JLabel();
        jLabel_cards_value = new javax.swing.JLabel();
        jLabel_payments_value = new javax.swing.JLabel();
        jLabel_transfers_value = new javax.swing.JLabel();
        jLabel_clients_serviced_value = new javax.swing.JLabel();
        jLabel_serviced_now = new javax.swing.JLabel();
        jLabel_serviced_all = new javax.swing.JLabel();
        jLabel_all_credits = new javax.swing.JLabel();
        jLabel_all_deposits = new javax.swing.JLabel();
        jLabel_all_cards = new javax.swing.JLabel();
        jLabel_all_payments = new javax.swing.JLabel();
        jLabel_all_transfers = new javax.swing.JLabel();
        jPanel_client = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_client = new javax.swing.JTable();
        jLabel_kolvo_clients = new javax.swing.JLabel();
        jLabel_clients_served = new javax.swing.JLabel();
        jLabel_clients_ochered = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_molod = new javax.swing.JLabel();
        jLabel_sred = new javax.swing.JLabel();
        jLabel_pojil = new javax.swing.JLabel();
        jLabel_kolvo_clients_value = new javax.swing.JLabel();
        jLabel_clients_served_value = new javax.swing.JLabel();
        jLabel_clients_ochered_value = new javax.swing.JLabel();
        jLabel_molod_value = new javax.swing.JLabel();
        jLabel_sred_value = new javax.swing.JLabel();
        jLabel_pojil_value = new javax.swing.JLabel();
        jLabel_ochered_now = new javax.swing.JLabel();
        jLabel_ochered_all = new javax.swing.JLabel();
        jLabel_all_molod = new javax.swing.JLabel();
        jLabel_all_sred = new javax.swing.JLabel();
        jLabel_all_pojil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Банковская очередь");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel_manage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSlider_speed.setMinimum(1);
        jSlider_speed.setValue(100);
        jSlider_speed.setInverted(true);
        jSlider_speed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_speedStateChanged(evt);
            }
        });

        jLabel_Speed.setText("Скорость");
        jLabel_Speed.setName(""); // NOI18N

        jButton_nachat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_nachat.setText("Начать");
        jButton_nachat.setToolTipText("");
        jButton_nachat.setName(""); // NOI18N
        jButton_nachat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nachatActionPerformed(evt);
            }
        });

        jButton_start.setText("Старт");
        jButton_start.setEnabled(false);
        jButton_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_startActionPerformed(evt);
            }
        });

        jButton_stop.setText("Стоп");
        jButton_stop.setEnabled(false);
        jButton_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_stopActionPerformed(evt);
            }
        });

        jLabel2.setText("Количество окошек");

        jSlider_new_clients.setMaximum(10);
        jSlider_new_clients.setValue(0);
        jSlider_new_clients.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_new_clientsStateChanged(evt);
            }
        });

        jLabel_new_clients.setText("Новые клиенты");

        jTextField_step.setEditable(false);
        jTextField_step.setText("0");

        jLabel_step.setText("Шаг");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel_manageLayout = new javax.swing.GroupLayout(jPanel_manage);
        jPanel_manage.setLayout(jPanel_manageLayout);
        jPanel_manageLayout.setHorizontalGroup(
            jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_manageLayout.createSequentialGroup()
                .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_manageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_nachat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_start, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_manageLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_manageLayout.createSequentialGroup()
                                .addComponent(jLabel_new_clients)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSlider_new_clients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_manageLayout.createSequentialGroup()
                                .addComponent(jLabel_Speed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSlider_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_manageLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jTextField_kolvoWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_manageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_step)
                        .addGap(48, 48, 48)
                        .addComponent(jTextField_step, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_manageLayout.setVerticalGroup(
            jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_manageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_manageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider_new_clients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_new_clients))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel_manageLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(jPanel_manageLayout.createSequentialGroup()
                        .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_nachat)
                            .addComponent(jButton_start)
                            .addComponent(jButton_stop)
                            .addComponent(jTextField_kolvoWindows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_manageLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Speed)
                                    .addComponent(jSlider_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_manageLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(jPanel_manageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_step)
                                    .addComponent(jTextField_step, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))))))
        );

        jPanel_window.setBorder(javax.swing.BorderFactory.createTitledBorder("Окошки"));

        jTable_window.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_window);

        jLabel_kolvo_windows.setText("Количество окошек");

        jLabel_clients_serviced.setText("Клиентов обслуживается");

        jLabel_kolvo_windows_value.setText("-");

        jLabel_serviced_operacion.setText("Обслуживаемые операции:");

        jLabel_credits.setText("Кредиты");

        jLabel_deposits.setText("Вклады");

        jLabel_cards.setText("Банковские карты");

        jLabel_payments.setText("Платежи");

        jLabel_transfers.setText("Переводы");

        jLabel_credits_value.setText("-");

        jLabel_deposits_value.setText("-");

        jLabel_cards_value.setText("-");

        jLabel_payments_value.setText("-");

        jLabel_transfers_value.setText("-");

        jLabel_clients_serviced_value.setText("-");

        jLabel_serviced_now.setText("Сейчас");

        jLabel_serviced_all.setText("Всего");

        jLabel_all_credits.setText("-");

        jLabel_all_deposits.setText("-");

        jLabel_all_cards.setText("-");

        jLabel_all_payments.setText("-");

        jLabel_all_transfers.setText("-");

        javax.swing.GroupLayout jPanel_windowLayout = new javax.swing.GroupLayout(jPanel_window);
        jPanel_window.setLayout(jPanel_windowLayout);
        jPanel_windowLayout.setHorizontalGroup(
            jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_windowLayout.createSequentialGroup()
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_windowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                    .addGroup(jPanel_windowLayout.createSequentialGroup()
                        .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_windowLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_clients_serviced)
                                    .addComponent(jLabel_kolvo_windows)
                                    .addComponent(jLabel_serviced_operacion)))
                            .addGroup(jPanel_windowLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_deposits)
                                    .addComponent(jLabel_credits)
                                    .addComponent(jLabel_cards)
                                    .addComponent(jLabel_payments)
                                    .addComponent(jLabel_transfers))))
                        .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_windowLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_serviced_now)
                                    .addGroup(jPanel_windowLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_deposits_value)
                                            .addComponent(jLabel_credits_value)
                                            .addComponent(jLabel_cards_value)
                                            .addComponent(jLabel_payments_value)
                                            .addComponent(jLabel_transfers_value))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_serviced_all)
                                    .addGroup(jPanel_windowLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_all_credits)
                                            .addComponent(jLabel_all_deposits)
                                            .addComponent(jLabel_all_cards)
                                            .addComponent(jLabel_all_payments)
                                            .addComponent(jLabel_all_transfers))))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel_windowLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_clients_serviced_value)
                                    .addComponent(jLabel_kolvo_windows_value))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel_windowLayout.setVerticalGroup(
            jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_windowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_kolvo_windows)
                    .addComponent(jLabel_kolvo_windows_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_clients_serviced)
                    .addComponent(jLabel_clients_serviced_value))
                .addGap(18, 18, 18)
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_serviced_operacion)
                    .addComponent(jLabel_serviced_now)
                    .addComponent(jLabel_serviced_all))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_credits)
                    .addComponent(jLabel_credits_value)
                    .addComponent(jLabel_all_credits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_deposits)
                    .addComponent(jLabel_deposits_value)
                    .addComponent(jLabel_all_deposits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cards)
                    .addComponent(jLabel_cards_value)
                    .addComponent(jLabel_all_cards))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_payments_value, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_payments)
                        .addComponent(jLabel_all_payments)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_windowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_transfers)
                    .addComponent(jLabel_transfers_value)
                    .addComponent(jLabel_all_transfers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_client.setBorder(javax.swing.BorderFactory.createTitledBorder("Клиенты"));

        jTable_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_client);

        jLabel_kolvo_clients.setText("Всего клиентов");

        jLabel_clients_served.setText("Клиентов обслужено");

        jLabel_clients_ochered.setText("Клиентов в очереди");

        jLabel1.setText("В очереди:");

        jLabel_molod.setText("Молодых");

        jLabel_sred.setText("Взрослых");

        jLabel_pojil.setText("Пожилых");

        jLabel_kolvo_clients_value.setText("-");

        jLabel_clients_served_value.setText("-");

        jLabel_clients_ochered_value.setText("-");

        jLabel_molod_value.setText("-");

        jLabel_sred_value.setText("-");

        jLabel_pojil_value.setText("-");

        jLabel_ochered_now.setText("Сейчас");

        jLabel_ochered_all.setText("Было");

        jLabel_all_molod.setText("-");

        jLabel_all_sred.setText("-");

        jLabel_all_pojil.setText("-");

        javax.swing.GroupLayout jPanel_clientLayout = new javax.swing.GroupLayout(jPanel_client);
        jPanel_client.setLayout(jPanel_clientLayout);
        jPanel_clientLayout.setHorizontalGroup(
            jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clientLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_clientLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel_ochered_now))
                    .addGroup(jPanel_clientLayout.createSequentialGroup()
                        .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_clients_served)
                            .addComponent(jLabel_clients_ochered)
                            .addGroup(jPanel_clientLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel_molod))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_clientLayout.createSequentialGroup()
                                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_pojil)
                                    .addComponent(jLabel_sred))
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_clientLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel_clients_ochered_value))
                            .addGroup(jPanel_clientLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_sred_value)
                                    .addComponent(jLabel_molod_value)
                                    .addComponent(jLabel_pojil_value)))
                            .addGroup(jPanel_clientLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_kolvo_clients_value)
                                    .addComponent(jLabel_clients_served_value)))))
                    .addComponent(jLabel_kolvo_clients))
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_clientLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_all_molod)
                            .addComponent(jLabel_all_sred)
                            .addComponent(jLabel_all_pojil))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_clientLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_ochered_all)
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_clientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel_clientLayout.setVerticalGroup(
            jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_clientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_kolvo_clients_value)
                    .addComponent(jLabel_kolvo_clients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_clients_served)
                    .addComponent(jLabel_clients_served_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_clients_ochered_value)
                    .addComponent(jLabel_clients_ochered))
                .addGap(32, 32, 32)
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_ochered_now)
                    .addComponent(jLabel_ochered_all))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_molod)
                    .addComponent(jLabel_molod_value)
                    .addComponent(jLabel_all_molod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sred)
                    .addComponent(jLabel_sred_value)
                    .addComponent(jLabel_all_sred))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pojil)
                    .addComponent(jLabel_pojil_value)
                    .addComponent(jLabel_all_pojil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel_manage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel_manage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ArrayList<WindowForTable> alWindows = new ArrayList<>();
    public class WindowForTable {
        public int number;
        public String operacion;
        public String client;
        public int timeToFree;
        public int servedClients;
        public WindowForTable(int number)
        {
            this.number = number;
            this.operacion = "-";
            this.client = "-";
            this.timeToFree = 0;
            this.servedClients = 0;
        }
        public WindowForTable(int number, int operacion, String client, int time, int serv)
        {
            this.number = number;
            switch(operacion)
            {
                case 0: this.operacion = "-"; break;
                case 1: this.operacion = "Кредиты"; break;
                case 2: this.operacion = "Вклады"; break;
                case 3: this.operacion = "Банковские карты"; break;
                case 4: this.operacion = "Платежи"; break;
                case 5: this.operacion = "Переводы"; break;
            }
            this.client = client;
            this.timeToFree = time;
            this.servedClients = serv;
        }
    }
   
TableModel tableModelWindows = new AbstractTableModel() {
    // список колонок колонок для таблички с окнами
    public final String[] colNames = {"№", "Операция", "Клиент", "Освободится", "Обслужил"};
    //это количество столбцов
    @Override
    public int getColumnCount() { return colNames.length; }
    // это количество строк (длина нашего ArrayList с данными)
    @Override
    public int getRowCount() { return alWindows.size();}
    // метод возвращает данные для ячейки таблицы
    @Override
    public Object getValueAt(int row, int col) 
    {
        WindowForTable windows = (WindowForTable) alWindows.get(row);
        switch (col) 
        {
            case 0: return windows.number;
            case 1: return windows.operacion;
            case 2: return windows.client;
            case 3: return windows.timeToFree;
            case 4: return windows.servedClients;
            default: return "";
        }
    }
    // этот метод возвращает имена столбцов
    @Override
    public String getColumnName(int column) {return colNames[column];}
    @Override
    public boolean isCellEditable(int row, int col) {return false;}
    @Override
    public void setValueAt(Object aValue, int row, int column) {}
    @Override
    public Class getColumnClass(int c) {return (String.class);}
};
    
    ArrayList<ClientForTable> alClients = new ArrayList<>();
    public class ClientForTable {
        public int number;
        public String name;
        public String operacion;
        public String age;
        public ClientForTable(int number, String name, int operacion, int age)
        {
            this.number = number;
            this.name = name;
            switch(operacion)
            {
                case 1: this.operacion = "Кредиты"; break;
                case 2: this.operacion = "Вклады"; break;
                case 3: this.operacion = "Банковские карты"; break;
                case 4: this.operacion = "Платежи"; break;
                case 5: this.operacion = "Переводы"; break;
            }
            switch(age)
            {
                case 1: this.age = "Молодой"; break;
                case 2: this.age = "Взрослый"; break;
                case 3: this.age = "Пожилой"; break;
            }
        }
    }
    
TableModel tableModelClients = new AbstractTableModel() {
    //список колонок для таблички с клиентами
    public final String[] colNames = {"№", "Имя", "Операция", "Возраст"};
    // это количество столбцов
    @Override
    public int getColumnCount() { return colNames.length; }
    // это количество строк (длина нашего ArrayList с данными)
    @Override
    public int getRowCount() { return alClients.size();}
    //метод возвращает данные для ячейки таблицы
    @Override
    public Object getValueAt(int row, int col) 
    {
        ClientForTable clients = (ClientForTable) alClients.get(row);
        switch (col) 
        {
            case 0: return clients.number;
            case 1: return clients.name;
            case 2: return clients.operacion; 
            case 3: return clients.age; 
            default: return "";
        }
    }
    // этот метод возвращает имена столбцов
    @Override
    public String getColumnName(int column) {return colNames[column];}
    @Override
    public boolean isCellEditable(int row, int col) {return false;}
    @Override
    public void setValueAt(Object aValue, int row, int column) {}
    @Override
    public Class getColumnClass(int c) {return (String.class);}
};
    
    /**Начать работу программы
     * 
     * @param evt 
     */
    private void jButton_nachatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nachatActionPerformed
        //вводим кол-во окошек
        int kw;
        try{
            kw = Integer.parseInt(jTextField_kolvoWindows.getText());
        } catch(NumberFormatException e)
        {
            kw = 10;
            String kolWinStr = ""+kw;
            jTextField_kolvoWindows.setText(kolWinStr);
        }
        jTextField_kolvoWindows.setEnabled(false);

        kolvoWindows = kw;
        bwindows = new BankWindow[kw];
        jLabel_kolvo_clients_value.setText(""+quene.getNumberClient());
        jLabel_kolvo_windows_value.setText(""+kolvoWindows);
        //создаем окошки
        for(int j=0; j<kw; j++)
        {
            bwindows[j] = new BankWindow(j+1);
            WindowForTable window = new WindowForTable(j+1);
            alWindows.add(window);
        }
        jTable_window.setModel(tableModelWindows);
        jTable_client.setModel(tableModelClients);
        
        jTable_window.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable_window.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTable_window.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTable_client.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable_client.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable_client.getColumnModel().getColumn(2).setPreferredWidth(100);
        
        jLabel_clients_ochered_value.setText(""+quene.getKolvoClients());
        jLabel_clients_served_value.setText(""+quene.getKolvoClients());
        
        jButton_nachat.setEnabled(false);
        jButton_start.setEnabled(true);
    }//GEN-LAST:event_jButton_nachatActionPerformed
    
    /**Стартовать 
     * 
     * @param evt 
     */
    private void jButton_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_startActionPerformed
        jButton_start.setEnabled(false);
        jButton_stop.setEnabled(true);
        timer.start();
    }//GEN-LAST:event_jButton_startActionPerformed
    /**Стоп
     * 
     * @param evt 
     */
    private void jButton_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_stopActionPerformed
        jButton_stop.setEnabled(false);
        jButton_start.setEnabled(true);
        timer.stop();
    }//GEN-LAST:event_jButton_stopActionPerformed
    /**Изменение скорости работы
     * 
     * @param evt 
     */
    private void jSlider_speedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_speedStateChanged
        delay = 10 * (jSlider_speed.getValue());
        timer.setDelay(delay);
    }//GEN-LAST:event_jSlider_speedStateChanged
    /**Изменение кол-ва новых клиентов от 0 до 10
     * 
     * @param evt 
     */
    private void jSlider_new_clientsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_new_clientsStateChanged
        newClients = jSlider_new_clients.getValue()+1;
    }//GEN-LAST:event_jSlider_new_clientsStateChanged
                
    
        int kolvoWindows = 0;//кол-во окошек
        BankWindow bwindows[];//массив окошек
        int step = 0;
        int delay = 1000;//время повтора таймера
        int newClients = 0;//для рандома создания клиентов (0 - не добавляются новые клиенты)
        int allCredits=0, allDeposits=0, allCards=0, allPayments=0, allTransfers=0;
        ClientQuene quene = new ClientQuene();//очередь клиентов
        java.util.Random rand = new java.util.Random();//для создания новых клиентов
        javax.swing.Timer timer = new javax.swing.Timer( delay, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                step++;
                jTextField_step.setText(""+step);
                //добавление новых клиентов в очередь
                quene.generateClient(rand, newClients);
                ///подсчет клиентов
                int kCredits=0,kDeposits=0,kCards=0,kPayments=0,kTransfers=0;
                int kServ=0;//обслужили все окошки вместе
                int kServiced=0;//обслуживается сейчас
                //обслуживание клиентов
                for(int j=0; j<kolvoWindows; j++)
                {
                    if(bwindows[j].isFree && quene.getKolvoClients()!=0)
                    {
                        jTextArea1.setText(jTextArea1.getText() +
                        "Клиент под номером " + quene.getClientIndex(0).getNumber() 
                        + " подойдите к окошку №" + bwindows[j].getNumber() +"\n");
                        bwindows[j].setClient(quene.pop_ochered());
                    }
                    if(!bwindows[j].isFree)
                    {
                        if(bwindows[j].getOperacion().getTime() == 1)
                            switch(bwindows[j].getIntOperacion())
                            {
                                case BankWindow.CREDITS_VALUE: allCredits++; break;
                                case BankWindow.DEPOSITS_VALUE: allDeposits++; break;
                                case BankWindow.CARDS_VALUE: allCards++; break;
                                case BankWindow.PAYMENTS_VALUE: allPayments++; break;
                                case BankWindow.TRANSFERS_VALUE: allTransfers++; break;
                            }
                        bwindows[j].Work();
                    }
                    kServ += bwindows[j].getCountServed();
                    if(!bwindows[j].isFree)
                        switch(bwindows[j].getIntOperacion())
                        {
                            case BankWindow.CREDITS_VALUE: kCredits++; break;
                            case BankWindow.DEPOSITS_VALUE: kDeposits++; break;
                            case BankWindow.CARDS_VALUE: kCards++; break;
                            case BankWindow.PAYMENTS_VALUE: kPayments++; break;
                            case BankWindow.TRANSFERS_VALUE: kTransfers++; break;
                        }
                    
                    //для таблицы
                    int serv = bwindows[j].getCountServed();
                    WindowForTable wind;
                    if(!bwindows[j].isFree)
                    {
                        String name = bwindows[j].getClient().getName();
                        int oper = bwindows[j].getIntOperacion();
                        int time = bwindows[j].getOperacion().getTime();
                        wind = new WindowForTable(j+1, oper, name, time, serv);
                    }
                    else
                    {
                        wind = new WindowForTable(j+1, 0, "-", 0, serv);
                    }
                    alWindows.set(j, wind);
                    
                    if(!bwindows[j].isFree)
                        kServiced++;
                }
                //подсчет клиентов в очереди
                int kc = quene.getKolvoClients();
                quene.kMolod = 0;
                quene.kSred = 0;
                quene.kPojil = 0;
                alClients.clear();
                for(int j=0; j<kc; j++)
                {
                    Client c = quene.countKolvoClients(j);
 
                    int number = c.getNumber();
                    String name = c.getName();
                    int oper = c.getIntOperacion();
                    int age = c.getAge();
                    ClientForTable cs = new ClientForTable(number, name, oper, age);
                    alClients.add(cs);
                }
                //вывод информации
                jLabel_molod_value.setText(""+quene.kMolod);
                jLabel_sred_value.setText(""+quene.kSred);
                jLabel_pojil_value.setText(""+quene.kPojil);
                jLabel_all_molod.setText(""+quene.allMolod);
                jLabel_all_sred.setText(""+quene.allSred);
                jLabel_all_pojil.setText(""+quene.allPojil);
                jLabel_kolvo_clients_value.setText(""+quene.getNumberClient());
                jLabel_clients_ochered_value.setText(""+kc);
                jLabel_credits_value.setText(""+kCredits);
                jLabel_deposits_value.setText(""+kDeposits);
                jLabel_cards_value.setText(""+kCards);
                jLabel_payments_value.setText(""+kPayments);
                jLabel_transfers_value.setText(""+kTransfers);
                jLabel_clients_serviced_value.setText(""+kServiced);
                jLabel_clients_served_value.setText(""+kServ);
                jLabel_all_credits.setText(""+allCredits);
                jLabel_all_deposits.setText(""+allDeposits);
                jLabel_all_cards.setText(""+allCards);
                jLabel_all_payments.setText(""+allPayments);
                jLabel_all_transfers.setText(""+allTransfers);
                jTable_window.repaint();
                jTable_client.repaint();
                jTable_client.getColumnModel().getColumn(3).setPreferredWidth(70);
                jTable_client.getColumnModel().getColumn(3).setPreferredWidth(71);
            }
        } );
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_nachat;
    private javax.swing.JButton jButton_start;
    private javax.swing.JButton jButton_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Speed;
    private javax.swing.JLabel jLabel_all_cards;
    private javax.swing.JLabel jLabel_all_credits;
    private javax.swing.JLabel jLabel_all_deposits;
    private javax.swing.JLabel jLabel_all_molod;
    private javax.swing.JLabel jLabel_all_payments;
    private javax.swing.JLabel jLabel_all_pojil;
    private javax.swing.JLabel jLabel_all_sred;
    private javax.swing.JLabel jLabel_all_transfers;
    private javax.swing.JLabel jLabel_cards;
    private javax.swing.JLabel jLabel_cards_value;
    private javax.swing.JLabel jLabel_clients_ochered;
    private javax.swing.JLabel jLabel_clients_ochered_value;
    private javax.swing.JLabel jLabel_clients_served;
    private javax.swing.JLabel jLabel_clients_served_value;
    private javax.swing.JLabel jLabel_clients_serviced;
    private javax.swing.JLabel jLabel_clients_serviced_value;
    private javax.swing.JLabel jLabel_credits;
    private javax.swing.JLabel jLabel_credits_value;
    private javax.swing.JLabel jLabel_deposits;
    private javax.swing.JLabel jLabel_deposits_value;
    private javax.swing.JLabel jLabel_kolvo_clients;
    private javax.swing.JLabel jLabel_kolvo_clients_value;
    private javax.swing.JLabel jLabel_kolvo_windows;
    private javax.swing.JLabel jLabel_kolvo_windows_value;
    private javax.swing.JLabel jLabel_molod;
    private javax.swing.JLabel jLabel_molod_value;
    private javax.swing.JLabel jLabel_new_clients;
    private javax.swing.JLabel jLabel_ochered_all;
    private javax.swing.JLabel jLabel_ochered_now;
    private javax.swing.JLabel jLabel_payments;
    private javax.swing.JLabel jLabel_payments_value;
    private javax.swing.JLabel jLabel_pojil;
    private javax.swing.JLabel jLabel_pojil_value;
    private javax.swing.JLabel jLabel_serviced_all;
    private javax.swing.JLabel jLabel_serviced_now;
    private javax.swing.JLabel jLabel_serviced_operacion;
    private javax.swing.JLabel jLabel_sred;
    private javax.swing.JLabel jLabel_sred_value;
    private javax.swing.JLabel jLabel_step;
    private javax.swing.JLabel jLabel_transfers;
    private javax.swing.JLabel jLabel_transfers_value;
    private javax.swing.JPanel jPanel_client;
    private javax.swing.JPanel jPanel_manage;
    private javax.swing.JPanel jPanel_window;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider_new_clients;
    private javax.swing.JSlider jSlider_speed;
    private javax.swing.JTable jTable_client;
    private javax.swing.JTable jTable_window;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_kolvoWindows;
    private javax.swing.JTextField jTextField_step;
    // End of variables declaration//GEN-END:variables
}
